apiVersion: v1
kind: Service
metadata:
  name: service-server
  labels:
    app: assemblyline
    section: core
    component: service-server
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: service-server
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
