apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-preview
spec:
  template:
    spec:
      containers:
        - name: demoapp
          env:
            - name: PREVIEW_ENV
              value: "true"
