- name: Check if Helm is already installed
  command: helm version --short
  register: helm_check
  failed_when: false
  changed_when: false

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_check.rc != 0

- name: Run Helm install script
  command: /tmp/get_helm.sh
  when: helm_check.rc != 0
