# Enable ingress and TLS
ingressAnnotations:
  kubernetes.io/ingress.class: "nginx"
  cert-manager.io/cluster-issuer: "letsencrypt-prod"
tlsSecretName: "assemblyline-tls"

# Use internal file storage
internalFilestore: true

# Storage classes
redisStorageClass: "local-path"
datastore:
  volumeClaimTemplate:
    storageClassName: "local-path"
log-storage:
  volumeClaimTemplate:
    storageClassName: "local-path"
persistentStorageClass: "local-path"

# Configure Assemblyline FQDN for HTTPS
configuration:
  ui:
    fqdn: "al.codepretzels.com"
  submission:
    max_file_size: 104857600
  logging:
    log_level: "INFO"

# Global resource tuning (apply to various components)
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

# Elastic helper fix
elasticHelper:
  initImage: docker.elastic.co/elasticsearch/elasticsearch:8.10.2

# Reduce heavy replicas for small clusters
elasticsearch:
  master:
    replicas: 1

filestore:
  replicas: 1

# Disable or reduce failing/optional services
services:
  zeek:
    enabled: false
  frankenstrings:
    enabled: false
  unpacme:
    replicas: 1
  yara:
    replicas: 1
