# Enable ingress and TLS
ingressAnnotations:
  kubernetes.io/ingress.class: "nginx"
  cert-manager.io/cluster-issuer: "letsencrypt-prod"
tlsSecretName: "assemblyline-tls"

# Use internal file storage
internalFilestore: true

# Storage classes
redisStorageClass: "local-path"
datastore:
  volumeClaimTemplate:
    storageClassName: "local-path"
log-storage:
  volumeClaimTemplate:
    storageClassName: "local-path"
persistentStorageClass: "local-path"

# Configure Assemblyline FQDN for HTTPS
configuration:
  ui:
    fqdn: "al.codepretzels.com"
  submission:
    max_file_size: 104857600  # 100MB
  logging:
    log_level: "ERROR"  # Reduce log volume to ease CPU/IO load

# Global resource tuning (applies to most components)
resources:
  requests:
    cpu: "20m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

# Elastic helper fix
elasticHelper:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "8.10.2"

# Reduce Elasticsearch footprint
elasticsearch:
  master:
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "200m"
        memory: "768Mi"

# Reduce filestore load
filestore:
  replicas: 1

# Disable or reduce failing/optional services
services:
  zeek:
    enabled: false
  frankenstrings:
    enabled: false
  yara:
    enabled: false
  unpacme:
    enabled: false
  apkaye:
    enabled: false
  tagcheck:
    enabled: false
  overpower:
    enabled: false
  espresso:
    enabled: false
  metapeek:
    enabled: false
  metadefender:
    enabled: false
  torrentslicer:
    enabled: false
  characterizer:
    enabled: false
  batchdeobfuscator:
    enabled: false
  swiffer:
    enabled: false
