apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: demoapp
image: 478047323853.dkr.ecr.us-east-1.amazonaws.com/demoapp:5fd3cd8145ddc7b5e31dcc724542bd409446ce74
          ports:
            - containerPort: 5000
