- name: Check k3s node health
  hosts: control_plane
  gather_facts: false

  tasks:
    - name: Check node status with kubectl
      command: kubectl get nodes -o wide
      register: node_status
      changed_when: false

    - name: Print node status
      debug:
        msg: "{{ node_status.stdout_lines }}"
