apiVersion: batch/v1
kind: Job
metadata:
  name: create-ecr-secret-{NAMESPACE}   # You will substitute {NAMESPACE}
  namespace: argocd-secrets             # This is where the job will run
spec:
  template:
    spec:
      serviceAccountName: default
      restartPolicy: OnFailure
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Creating ECR imagePullSecret for {NAMESPACE}..."
              aws ecr get-login-password --region us-east-1 | \
              kubectl create secret docker-registry regcred \
                --docker-server=478047323853.dkr.ecr.us-east-1.amazonaws.com \
                --docker-username=AWS \
                --docker-password-stdin \
                --namespace={NAMESPACE}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: argo-aws-creds
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: argo-aws-creds
                  key: aws_secret_access_key
