apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yml
  - ingress-patch.yml
  - namespace.yml

namePrefix: demoapp-pr-
