apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demoapp-pr123

resources:
  - ../../base
  - create-ecr-secret-job.yaml
  - rbac.yaml

helmCharts:
  - name: demoapp
    releaseName: demoapp-preview
    version: 0.1.0
    repo: file://../../base
    valuesFile: values-preview.yaml

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
