apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demoapp-pr123

resources:
  - ../../base
  - create-ecr-secret-job.yaml
  - rbac.yaml

patchesStrategicMerge:
  - patches/deployment-patch.yaml
  - patches/ingress-patch.yaml

configMapGenerator:
  - name: preview-values
    files:
      - values.yaml=values-preview.yaml

generatorOptions:
  disableNameSuffixHash: true
