apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-secret-create
  namespace: demoapp-pr123
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-secret-create-binding
  namespace: demoapp-pr123
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argocd-secrets
roleRef:
  kind: Role
  name: allow-secret-create
  apiGroup: rbac.authorization.k8s.io
