name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: demoapp
  ECR_REGISTRY: 478047323853.dkr.ecr.us-east-1.amazonaws.com
  PR_NUMBER: ${{ github.event.pull_request.number }}
  IMAGE_TAG: pr-${{ github.sha }}
  APP_NAME: demoapp-pr${{ github.event.pull_request.number }}
  PR_DOMAIN: pr${{ github.event.pull_request.number }}.codepretzels.com
  NAMESPACE: demoapp-pr${{ github.event.pull_request.number }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug AWS identity
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}        

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
            docker login --username AWS --password-stdin $ECR_REGISTRY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./apps/demoapp
          file: ./apps/demoapp/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Generate imagePullSecret manifest
        run: bash scripts/gen-image-pull-secret.sh ${NAMESPACE} apps/demoapp/overlays/preview/image-pull-secret.yaml

      - name: Replace patch values
        run: |
          sed -i "s|REPLACE_IMAGE_TAG|${IMAGE_TAG}|g" apps/demoapp/overlays/preview/deployment-patch.yaml
          sed -i "s|REPLACE_PR_DOMAIN|${PR_DOMAIN}|g" apps/demoapp/overlays/preview/ingress-patch.yaml


      - name: Generate ECR secret job manifest with echo
        run: |
          echo "apiVersion: batch/v1" > apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "kind: Job" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "metadata:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "  name: create-ecr-secret-${NAMESPACE}" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "  namespace: argocd-secrets" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "spec:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "  template:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "    spec:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "      serviceAccountName: default" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "      restartPolicy: OnFailure" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "      containers:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "        - name: aws-cli" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "          image: amazon/aws-cli" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "          command: [\"/bin/sh\", \"-c\"]" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "          args:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "            - |" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "              echo \"Creating ECR imagePullSecret for ${NAMESPACE}...\"" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "              aws ecr get-login-password --region ${AWS_REGION} | \\" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "              kubectl create secret docker-registry regcred \\" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                --docker-server=${ECR_REGISTRY} \\" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                --docker-username=AWS \\" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                --docker-password-stdin \\" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                --namespace=${NAMESPACE}" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "          env:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "            - name: AWS_ACCESS_KEY_ID" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "              valueFrom:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                secretKeyRef:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                  name: argo-aws-creds" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                  key: aws_access_key_id" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "            - name: AWS_SECRET_ACCESS_KEY" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "              valueFrom:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                secretKeyRef:" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                  name: argo-aws-creds" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml
          echo "                  key: aws_secret_access_key" >> apps/demoapp/overlays/preview/create-ecr-secret-job.yaml



      - name: Generate RBAC manifest dynamically
        run: |
          echo "apiVersion: rbac.authorization.k8s.io/v1" > apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "kind: Role" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "metadata:" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "  name: allow-secret-create" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "  namespace: ${NAMESPACE}" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "rules:" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "- apiGroups: [\"\"]" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "  resources: [\"secrets\"]" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          echo "  verbs: [\"create\"]" >> apps/demoapp/overlays/preview/secret-rbac.yaml
          # Add the RoleBinding below...



      - name: Generate namespace manifest dynamically
        run: |
          echo "apiVersion: v1" > apps/demoapp/overlays/preview/namespace.yaml
          echo "kind: Namespace" >> apps/demoapp/overlays/preview/namespace.yaml
          echo "metadata:" >> apps/demoapp/overlays/preview/namespace.yaml
          echo "  name: ${NAMESPACE}" >> apps/demoapp/overlays/preview/namespace.yaml

      - name: Debug namespace.yaml
        run: cat apps/demoapp/overlays/preview/namespace.yaml

      - name: Commit PR-specific patch changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -f apps/demoapp/overlays/preview/namespace.yaml
          git add -f apps/demoapp/overlays/preview/deployment-patch.yaml
          git add -f apps/demoapp/overlays/preview/ingress-patch.yaml
          git add -f apps/demoapp/overlays/preview/image-pull-secret.yaml
          git commit -m "Update PR #${PR_NUMBER} namespace and ArgoCD patches" || echo "No changes"
          git push origin HEAD:${{ github.head_ref }}

      - name: Login to ArgoCD
        run: |
          argocd login argo.codepretzels.com \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: Deploy Preview App with ArgoCD
        run: |
          argocd app create ${APP_NAME} \
            --repo https://github.com/kernelpanic09/k3s_lab.git \
            --path apps/demoapp/overlays/preview \
            --revision ${{ github.head_ref }} \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace ${NAMESPACE} \
            --upsert

          argocd app sync ${APP_NAME}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: [self-hosted, linux]

    steps:
      - name: Delete ArgoCD App and Namespace
        run: |
          argocd app delete demoapp-pr${{ github.event.pull_request.number }} --yes || true
          kubectl delete namespace demoapp-pr${{ github.event.pull_request.number }} || true
