name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: demoapp
  ECR_REGISTRY: 478047323853.dkr.ecr.us-east-1.amazonaws.com
  PR_NUMBER: ${{ github.event.pull_request.number }}
  IMAGE_TAG: pr-${{ github.sha }}
  APP_NAME: demoapp-pr${{ github.event.pull_request.number }}
  PR_DOMAIN: pr${{ github.event.pull_request.number }}.codepretzels.com
  NAMESPACE: demoapp-pr${{ github.event.pull_request.number }}

jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug AWS identity
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}        

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./apps/demoapp
          file: ./apps/demoapp/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64


      - name: Replace patch values
        run: |
          sed -i "s|REPLACE_IMAGE_TAG|${IMAGE_TAG}|g" apps/demoapp/overlays/preview/deployment-patch.yaml
          sed -i "s|REPLACE_PR_DOMAIN|${PR_DOMAIN}|g" apps/demoapp/overlays/preview/ingress-patch.yaml
          sed -i "s|REPLACE_PR_NUMBER|${PR_NUMBER}|g" apps/demoapp/overlays/preview/namespace.yaml

      - name: Deploy Preview App with ArgoCD
        run: |
          argocd app create ${APP_NAME} \
            --repo https://github.com/kernelpanic09/k3s_lab.git \
            --path apps/demoapp/overlays/preview \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace ${NAMESPACE} \
            --upsert

          argocd app sync ${APP_NAME}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: [self-hosted, linux]

    steps:
      - name: Delete ArgoCD App and Namespace
        run: |
          argocd app delete demoapp-pr${{ github.event.pull_request.number }} --yes || true
          kubectl delete namespace demoapp-pr${{ github.event.pull_request.number }} || true
